apiVersion: v1
kind: Service
metadata:
  name: stylehub-user-service
  namespace: stylehub
  labels:
    app: stylehub-user-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: stylehub-user-service
