apiVersion: v1
kind: ConfigMap
metadata:
  name: stylehub-config
  namespace: stylehub
  labels:
    app: stylehub
    component: config
data:
  # Frontend Configuration
  REACT_APP_API_BASE_URL: "http://stylehub-api-service:8080"
  REACT_APP_ENVIRONMENT: "production"
  
  # Product Service Configuration
  PRODUCT_SERVICE_PORT: "8081"
  PRODUCT_SERVICE_HOST: "0.0.0.0"
  
  # User Service Configuration
  USER_SERVICE_PORT: "8082"
  USER_SERVICE_HOST: "0.0.0.0"
  
  # Cart Service Configuration
  CART_SERVICE_PORT: "8083"
  CART_SERVICE_HOST: "0.0.0.0"
  
  # Order Service Configuration
  ORDER_SERVICE_PORT: "8084"
  ORDER_SERVICE_HOST: "0.0.0.0"
  
  # Database Configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "stylehub"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: stylehub
  labels:
    app: stylehub
    component: nginx
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      upstream frontend {
        server stylehub-ui-service:80;
      }
      
      upstream api {
        server stylehub-api-service:8080;
      }
      
      server {
        listen 80;
        server_name localhost;
        
        location / {
          proxy_pass http://frontend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/ {
          proxy_pass http://api/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
