apiVersion: v1
kind: Namespace
metadata:
  name: stylehub
  labels:
    name: stylehub
    environment: production
  annotations:
    description: "Namespace for StyleHub e-commerce application"
---
# Resource Quotas for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stylehub-quota
  namespace: stylehub
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    configmaps: "10"
    secrets: "10"
