name: Product Service CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/product-service/**'
      - 'kubernetes/product-service/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/product-service/**'
      - 'kubernetes/product-service/**'

jobs:
  product-service:
    uses: ./.github/workflows/backend-service-ci-cd.yml
    with:
      service-name: product-service
      service-path: backend/product-service
      service-port: "8081"
      dockerfile-path: backend/product-service/Dockerfile
      requirements-path: backend/product-service/requirements.txt
    secrets: inherit
